### ISSUE TITLE
C11 external atomic lifo test fails with LLVM

### ISSUE THREAD

**Issue by abouteiller** [ICLDisco/parsec#296]
**[Original report](https://bitbucket.org/icldistcomp/parsec/issue/296) by me.**

----------------------------------------

C11 Atomics \(LLVM based\) fail the lifo test on Spock. Interestingly, all other atomic tests pass \(including lifo:inline\) and the rest of Parsec Ctest do not implode \(we use the ‘inline’ variants in most cases\). 

```c
ctest --output-on-failure --timeout 20 -R lifo --verbose                                                                                                                ─╯
test 6
    Start  6: class/lifo

6: Test command: /ccs/home/bouteilla/parsec/dplasma/parsec/spock.debug/tests/class/lifo
6: Test timeout computed to be: 20
1/2 Test  #6: class/lifo .......................***Exception: SegFault  0.28 sec

test 13
    Start 13: class/lifo:inline

13: Test command: /ccs/home/bouteilla/parsec/dplasma/parsec/spock.debug/tests/class/lifo_inline
13: Test timeout computed to be: 20
13: Sequential test.
13:  - create 8192 random elements and push them in lifo1
13:  - pop them from lifo1, check they are ok, and push them back in lifo2
13:  - pop them from lifo2, check they are ok, and push them back in lifo1
13: Parallel test.
13:  - translate elements from lifo1 to lifo2 or from lifo2 to lifo1 (random), [1000000 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/1000000) times on 1 threads
13: == Time to move [1000000 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/1000000) times per thread for 1 threads from l1 to l2 or l2 to l1 randomly:
13: == MIN [77116801 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/77116801) nanosecond
13: == MAX [77116801 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/77116801) nanosecond
13: == AVG 7.71168e+07 nanosecond
13:  - move all elements to lifo1
13:  - pop them from lifo1, check they are ok, push them back in lifo2, and check they are all there
13:  - pop all elements from lifo1, and free them
13:  - pop all elements from lifo2, and free them
13:  - all tests passed
2/2 Test #13: class/lifo:inline ................   Passed    0.40 sec




❯ gdb --args /ccs/home/bouteilla/parsec/dplasma/parsec/spock.debug/tests/class/lifo                                                                                       ─╯

[New Thread 0x7fffe4847700 (LWP 24464)]
Sequential test.
 - create 8192 random elements and push them in lifo1
 - pop them from lifo1, check they are ok, and push them back in lifo2

Thread 1 "lifo" received signal SIGSEGV, Segmentation fault.
0x00007fffed905f4f in parsec_atomic_cas_int128 (location=0x2071c8 <lifo1+32>, old_value=1547859506823149350983565312, new_value=1547843863984174845283794945)
    at /ccs/home/bouteilla/parsec/dplasma/parsec/parsec/include/parsec/sys/atomic-c11.h:60
60          return atomic_compare_exchange_strong( (_Atomic __int128_t*)location, &old_value, new_value );
Missing separate debuginfos, use: zypper install libatomic1-debuginfo-9.3.1+git1296-1.6.1.x86_64 libibverbs-debuginfo-51mlnx1-1.51237.x86_64 libnl3-200-debuginfo-3.3.0-1.29.x86_64 librdmacm-debuginfo-51mlnx1-1.51237.x86_64
(gdb) bt
#0  0x00007fffed905f4f in parsec_atomic_cas_int128 (location=0x2071c8 <lifo1+32>, old_value=1547859506823149350983565312, new_value=1547843863984174845283794945)
    at /ccs/home/bouteilla/parsec/dplasma/parsec/parsec/include/parsec/sys/atomic-c11.h:60
#1  0x00007fffed905ecc in parsec_update_counted_pointer (addr=0x2071c8 <lifo1+32>, old=..., item=0x50058b0)
    at /ccs/home/bouteilla/parsec/dplasma/parsec/parsec/class/lifo.h:244
#2  0x00007fffed90617a in parsec_lifo_pop (lifo=0x2071a8 <lifo1>) at /ccs/home/bouteilla/parsec/dplasma/parsec/parsec/class/lifo.h:307
#3  0x000000000020377d in check_translate_inorder (l1=0x2071a8 <lifo1>, l2=0x2071d8 <lifo2>, lifo1name=0x2015d2 "lifo1", lifo2name=0x201752 "lifo2")
    at /ccs/home/bouteilla/parsec/dplasma/parsec/tests/class/lifo.c:116
#4  0x000000000020311d in main (argc=1, argv=0x7fffffff87c8) at /ccs/home/bouteilla/parsec/dplasma/parsec/tests/class/lifo.c:272
(gdb) list
55      ATOMIC_STATIC_INLINE
56      int parsec_atomic_cas_int128(volatile __int128_t* location,
57                                   __int128_t old_value,
58                                   __int128_t new_value)
59      {
60          return atomic_compare_exchange_strong( (_Atomic __int128_t*)location, &old_value, new_value );
61      }
62      #endif  /* defined(PARSEC_HAVE_INT128) */
63
64      /* Mask Operations */
(gdb) up
#1  0x00007fffed905ecc in parsec_update_counted_pointer (addr=0x2071c8 <lifo1+32>, old=..., item=0x50058b0)
    at /ccs/home/bouteilla/parsec/dplasma/parsec/parsec/class/lifo.h:244
244         return parsec_atomic_cas_int128(&addr->value, old.value, elem.value);
(gdb) p addr
$1 = (volatile parsec_counted_pointer_t *) 0x2071c8 <lifo1+32>
(gdb)  p old
$2 = {data = {guard = {counter = 0, lock = {_Value = false}}, item = 0x5005c00}, value = [1547859506823149350983565312 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/1547859506823149350983565312)}
(gdb) p elem
$3 = {data = {guard = {counter = 1, lock = {_Value = true}}, item = 0x50058b0}, value = [1547843863984174845283794945 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/1547843863984174845283794945)}
(gdb) p addr->value
$4 = [1547859506823149350983565312 (bb)](https://bitbucket.org/icldistcomp/parsec/commits/1547859506823149350983565312)
```

‌

config.log

```
 50 -- The C compiler identification is Clang 11.0.0
 51 -- Cray Programming Environment 2.7.6 C
 
 66 -- Compiler support for C11 detected and enabled

 91 -- Check size of __int128_t
 92 -- Check size of __int128_t - done
 93 -- Performing Test PARSEC_COMPILER_C11_COMPLIANT
 94 -- Performing Test PARSEC_COMPILER_C11_COMPLIANT - Success
 95 -- Performing Test PARSEC_STDC_HAVE_C11_ATOMICS
 96 -- Performing Test PARSEC_STDC_HAVE_C11_ATOMICS - Success
 97 -- Looking for include file stdatomic.h
 98 -- Looking for include file stdatomic.h - found
 99 -- Performing Test PARSEC_ATOMIC_USE_C11_32
100 -- Performing Test PARSEC_ATOMIC_USE_C11_32 - Success
101 -- Performing Test PARSEC_ATOMIC_USE_C11_64
102 -- Performing Test PARSEC_ATOMIC_USE_C11_64 - Success
103 -- Performing Test PARSEC_ATOMIC_USE_C11_128
104 -- Performing Test PARSEC_ATOMIC_USE_C11_128 - Success
105 -- > support for 32 bits atomics - found
106 -- > support for 64 bits atomics - found
107 -- > support for 128 bits atomics - found
```

‌

**Comment by abouteiller** [comment]
resolved in 99bd69ace90cd64a7bfe6320c9352ee0d2cafce8
