### ISSUE TITLE
Trivial parsec test fails

### ISSUE THREAD

**Issue by therault** [ICLDisco/parsec#545]
## Describe the bug
The following code fails in debug mode:

```
#include "parsec.h"

int main(int argc, char *argv[])
{
    parsec_context_t *parsec = parsec_init(&argc, &argv, -1);
    parsec_fini(parsec);
}
```

### To Reproduce
1. Checkout version master
2. Compile test above with PARSEC_DEBUG_VERBOSE ON
3. Run test

### Expected behavior
An assert about a non-initialized object in `parsec_ce` will trigger.

## Environment (please complete the following information):
This should be portable to all MPI-enabled environments.

**Comment by bosilca** [comment]
Ahem ;) Incorrect use of the parsec API.

```c
#include "parsec.h"

int main(int argc, char *argv[])
{
    parsec_context_t *parsec = parsec_init(-1, &argc, &argv);
    parsec_fini(&parsec);
}
```

**Comment by therault** [comment]
Sorry, my example was wrong.

With &parsec, it still fails: we unconditionally PARSEC_OBJ_RELEASE()
static globals in parsec_mpi_funnelled.c, and in PARSEC_DEBUG_PARANOID
mode, we do `assert(NULL != ((parsec_object_t *) (object))->obj_class);` in
the PARSEC_OBJ_DESTRUCT() call stack.

**Comment by bosilca** [comment]
Here is what I get on current master when I run this test.
```
x@-0001 MPI was not initialized. This version of PaRSEC was compiled with MPI datatype supports and *needs* MPI to execute.
	* Please initialized MPI in the application (MPI_Init/MPI_Init_thread) prior to initializing PaRSEC.
	* Alternatively, compile a version of PaRSEC without MPI (-DPARSEC_DIST_WITH_MPI=OFF in ccmake)
 @remote_dep_dequeue_init:230   (mone.nomads.utk.edu:19006)
Process 19006 exited with status = 250 (0x000000fa)
```

**Comment by bosilca** [comment]
```c
#include <mpi.h>
#include "parsec.h"

int main(int argc, char *argv[])
{
    MPI_Init(NULL, NULL);
    parsec_context_t *parsec = parsec_init(-1, &argc, &argv);
    parsec_fini(&parsec);
    MPI_Finalize();
}
```

**Comment by therault** [comment]
Correct...

Here is what I get in PARSEC_DEBUG_PARANOID=ON and PARSEC_DEBUG_NOISIER=ON:

```
(gdb) r
Starting program:
/home/herault/Documents/Recherche/parsec/parsec-master/build/tests/trivial
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 89420]
[New Thread 0x7ffff70f2000 (LWP 89426)]
[New Thread 0x7ffff5817000 (LWP 89427)]
***@***.*** MPI was not initialized with the appropriate level of thread
support.
* Current level is MPI_THREAD_SINGLE, while MPI_THREAD_SERIALIZED or
MPI_THREAD_MULTIPLE is needed
* to guarantee correctness of the PaRSEC runtime.
***@***.*** /!\ DEBUG LEVEL WILL PROBABLY REDUCE THE PERFORMANCE OF THIS RUN
/!\.
[New Thread 0x7fffc9fff000 (LWP 89428)]
[New Thread 0x7fffc97fe000 (LWP 89429)]
[New Thread 0x7fffc8ffd000 (LWP 89430)]
[New Thread 0x7fffc3fff000 (LWP 89431)]
[New Thread 0x7fffc37fe000 (LWP 89432)]
[New Thread 0x7fffc2ffd000 (LWP 89433)]
[New Thread 0x7fffc27fc000 (LWP 89434)]
[New Thread 0x7fffc1ffb000 (LWP 89435)]
[Thread 0x7fffc1ffb000 (LWP 89435) exited]
trivial:
/home/herault/Documents/Recherche/parsec/parsec-master/parsec/parsec_mpi_funnelled.c:612:
mpi_funnelled_fini: Assertion `PARSEC_OBJ_MAGIC_ID == ((parsec_object_t *)
(&mpi_funnelled_dynamic_sendreq_fifo))->obj_magic_id' failed.
[Thread 0x7fffc27fc000 (LWP 89434) exited]
[Thread 0x7fffc2ffd000 (LWP 89433) exited]
[Thread 0x7fffc37fe000 (LWP 89432) exited]
[Thread 0x7fffc3fff000 (LWP 89431) exited]
[Thread 0x7fffc8ffd000 (LWP 89430) exited]
[Thread 0x7fffc97fe000 (LWP 89429) exited]

Thread 1 "trivial" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737338638336)
at ./nptl/pthread_kill.c:44
44 ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6,
threadid=140737338638336) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737338638336) at
./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737338638336, ***@***.***=6) at
./nptl/pthread_kill.c:89
#3  0x00007ffff7bee476 in __GI_raise ***@***.***=6) at
../sysdeps/posix/raise.c:26
#4  0x00007ffff7bd47f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7bd471b in __assert_fail_base (fmt=0x7ffff7d89150
"%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x7ffff7f5e3e8 "PARSEC_OBJ_MAGIC_ID == ((parsec_object_t *)
(&mpi_funnelled_dynamic_sendreq_fifo))->obj_magic_id",
    file=0x7ffff7f5de68
"/home/herault/Documents/Recherche/parsec/parsec-master/parsec/parsec_mpi_funnelled.c",
line=612, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007ffff7be5e96 in __GI___assert_fail (
    assertion=0x7ffff7f5e3e8 "PARSEC_OBJ_MAGIC_ID == ((parsec_object_t *)
(&mpi_funnelled_dynamic_sendreq_fifo))->obj_magic_id",
    file=0x7ffff7f5de68
"/home/herault/Documents/Recherche/parsec/parsec-master/parsec/parsec_mpi_funnelled.c",
line=612,
    function=0x7ffff7f5ea50 <__PRETTY_FUNCTION__.16> "mpi_funnelled_fini")
at ./assert/assert.c:101
#7  0x00007ffff7e526e1 in mpi_funnelled_fini (ce=0x7ffff7fb9680 <parsec_ce>)
    at
/home/herault/Documents/Recherche/parsec/parsec-master/parsec/parsec_mpi_funnelled.c:612
#8  0x00007ffff7e50a69 in parsec_comm_engine_fini
(comm_engine=0x7ffff7fb9680 <parsec_ce>)
    at
/home/herault/Documents/Recherche/parsec/parsec-master/parsec/parsec_comm_engine.c:30
#9  0x00007ffff7e3f340 in parsec_fini (pcontext=0x7fffffffde30) at
/home/herault/Documents/Recherche/parsec/parsec-master/parsec/parsec.c:1220
#10 0x0000555555555499 in main (argc=1, argv=0x7fffffffdf58) at
/home/herault/Documents/Recherche/parsec/parsec-master/tests/trivial.c:8
(gdb)
```
